# Default values for http-server.
nameOverride: ""

image:
  repository: http-server
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  name: http-server
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080

deployment:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 40Mi

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetAverageValue: 80Mi
